# Generated by Django 3.2.7 on 2023-10-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_numder',
            new_name='property_number',
        ),
    ]
